### ISSUE TITLE
Compile issue

### ISSUE THREAD

**Issue by schenlap** [moshe-braner/Open-Glider-Network-Groundstation#9]
First i had to remove the EEPROM folder from ESP32 platform, as it used this instead of the one from the repo.

with current main an following the build instruction i get:

`~/Arduino/libraries/EEPROM/EEPROM.h:32:10: fatal error: ti/drivers/NVS.h: No such file or directory`
This is the libraray folder from the repo.

**Comment by schenlap** [comment]
Can you explain which lib is needed for this?

**Comment by moshe-braner** [comment]
Should not have to remove the EEPROM library from the ESP32 support package - OGNbase uses it.  This repo only has an EEPROM.cpp and .h files.  The line #include <EEPROM.h> should find the library file with that same name.  What error message did you get when compiling with the EEPROM folder in place?  The problem is more likely an incompatible version of some library - that's always the time-consuming part.  I use ESP Core v2.0.3.

**Comment by moshe-braner** [comment]
That said, OGNbase makes minimal use of the EEPROM since it stores the important settings in the config.json file instead.  The EEPROM settings can stay at their defaults.  So could probably remove the references to the EEPROM library from EEPROM.cpp & EEPROM.h?  But it does compile for me as it is.
